#!/bin/bash

# Copyright 2025 mjbots Robotic Systems, LLC.  info@mjbots.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

# Debug output
echo "=== Mypy Test Debug ==="
echo "PWD: $PWD"
echo "Script (\$0): $0"
echo "BUILD_WORKSPACE_DIRECTORY: ${BUILD_WORKSPACE_DIRECTORY:-not set}"
echo "BUILD_WORKING_DIRECTORY: ${BUILD_WORKING_DIRECTORY:-not set}"
echo "TEST_SRCDIR: ${TEST_SRCDIR:-not set}"
echo "RUNFILES_DIR: ${RUNFILES_DIR:-not set}"

# Find the workspace root by looking for WORKSPACE file
find_workspace_root() {
    local dir="$1"
    while [[ "$dir" != "/" ]]; do
        if [[ -f "$dir/WORKSPACE" ]]; then
            echo "$dir"
            return 0
        fi
        dir="$(dirname "$dir")"
    done
    return 1
}

WORKSPACE_ROOT=""

# Try BUILD_WORKSPACE_DIRECTORY first (set by bazel for local tests)
if [[ -n "$BUILD_WORKSPACE_DIRECTORY" ]]; then
    WORKSPACE_ROOT="$BUILD_WORKSPACE_DIRECTORY"
    echo "Using BUILD_WORKSPACE_DIRECTORY: $WORKSPACE_ROOT"
fi

# Try BUILD_WORKING_DIRECTORY (another bazel env var)
if [[ -z "$WORKSPACE_ROOT" && -n "$BUILD_WORKING_DIRECTORY" ]]; then
    if WORKSPACE_ROOT="$(find_workspace_root "$BUILD_WORKING_DIRECTORY")"; then
        echo "Found workspace via BUILD_WORKING_DIRECTORY: $WORKSPACE_ROOT"
    fi
fi

# Try to find workspace from current directory
if [[ -z "$WORKSPACE_ROOT" ]]; then
    if WORKSPACE_ROOT="$(find_workspace_root "$PWD")"; then
        echo "Found workspace from PWD: $WORKSPACE_ROOT"
    fi
fi

# Try to find workspace from script location (resolve symlinks)
if [[ -z "$WORKSPACE_ROOT" ]]; then
    SCRIPT_REAL="$(readlink -f "$0" 2>/dev/null || realpath "$0" 2>/dev/null || echo "$0")"
    SCRIPT_DIR="$(dirname "$SCRIPT_REAL")"
    echo "Script real path: $SCRIPT_REAL"
    echo "Script dir: $SCRIPT_DIR"
    if WORKSPACE_ROOT="$(find_workspace_root "$SCRIPT_DIR")"; then
        echo "Found workspace from script location: $WORKSPACE_ROOT"
    fi
fi

if [[ -z "$WORKSPACE_ROOT" ]]; then
    echo "ERROR: Could not find workspace root" >&2
    echo "Listing current directory:"
    ls -la "$PWD" | head -20
    echo "Listing parent directories from PWD:"
    dir="$PWD"
    for i in 1 2 3 4 5; do
        echo "  $dir contents: $(ls "$dir" 2>/dev/null | head -10 | tr '\n' ' ')"
        dir="$(dirname "$dir")"
    done
    exit 1
fi

MOTEUS_DIR="$WORKSPACE_ROOT/lib/python/moteus"
echo "MOTEUS_DIR: $MOTEUS_DIR"

if [[ ! -d "$MOTEUS_DIR" ]]; then
    echo "ERROR: $MOTEUS_DIR does not exist" >&2
    echo "Contents of $WORKSPACE_ROOT/lib/python:"
    ls -la "$WORKSPACE_ROOT/lib/python" 2>&1 || echo "  (directory not found)"
    exit 1
fi

# Create stub version.py if it doesn't exist (real one is generated by bazel)
VERSION_FILE="$MOTEUS_DIR/version.py"
CREATED_VERSION=false
if [[ ! -f "$VERSION_FILE" ]]; then
    echo "Creating stub version.py"
    echo 'VERSION = "0.0.0-dev"' > "$VERSION_FILE"
    CREATED_VERSION=true
fi

# Run mypy on the moteus package
echo "Running: mypy $MOTEUS_DIR --ignore-missing-imports"
mypy "$MOTEUS_DIR" --ignore-missing-imports
RESULT=$?

# Clean up stub version.py if we created it
if [[ "$CREATED_VERSION" == "true" ]]; then
    echo "Removing stub version.py"
    rm "$VERSION_FILE"
fi

exit $RESULT
